### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Agzes** [nperovic/GuiEnhancerKit#1]
**Hi!** 
I recently found your repository and would really like to use it, but there is one thing, but for some reason your code does not want to work at the same time in Visual Studio Code with plugins, it displays normally without a single error, but if I want to run it, then I teach an error with syntax!

Error: 
`(232) : ==> Syntax error.`

**Comment by nperovic** [comment]
> **Hi!** I recently found your repository and would really like to use it, but there is one thing, but for some reason your code does not want to work at the same time in Visual Studio Code with plugins, it displays normally without a single error, but if I want to run it, then I teach an error with syntax!
> 
> Error: `(232) : ==> Syntax error.`

Thank you for reporting this issue. It has been resolved at the following commit: d24ba6b18b5ba99521e1ce748b15ff2b2a785a3e.
